from typing import Literal

ALLOW_EXTS: frozenset[str] = frozenset(
    {
        ".m",
        ".mlx",
        ".slx",
        ".mdl",
        ".mat",
        ".prj",
        ".ssc",
        ".fig",
        ".sldd",
        ".mldatx",
        ".slreqx",
        ".sltx",
        ".txt",
        ".md",
        ".csv",
        ".json",
        ".xml",
        ".yaml",
        ".yml",
        ".png",
        ".jpg",
        ".jpeg",
        ".svg",
        ".pdf",
        ".bmp",
        ".gif",
        ".tif",
        ".tiff",
        ".webp",
    }
)

DENY_EXTS: frozenset[str] = frozenset(
    {
        ".exe",
        ".bat",
        ".cmd",
        ".com",
        ".scr",
        ".msi",
        ".dll",
        ".cpl",
        ".sys",
        ".drv",
        ".ocx",
        ".so",
        ".dylib",
        ".sh",
        ".bash",
        ".zsh",
        ".command",
        ".app",
        ".dmg",
        ".pkg",
        ".run",
        ".bin",
        ".elf",
        ".out",
        ".appimage",
        ".py",
        ".pyc",
        ".pyo",
        ".pyd",
        ".ps1",
        ".vbs",
        ".js",
        ".mex",
        ".mexw64",
        ".mexa64",
        ".mexmaci64",
        ".p",
        ".mlappinstall",
        ".mlpkginstall",
        ".ctf",
        ".lnk",
        ".url",
        ".scf",
        ".hta",
        ".wsf",
        ".wsh",
        ".jse",
        ".vbe",
        ".psm1",
        ".reg",
        ".inf",
        ".docm",
        ".xlsm",
        ".pptm",
        ".xlam",
        ".xlsb",
        ".class",
        ".jar",
        ".war",
        ".ear",
        ".wasm",
        ".mjs",
        ".cjs",
    }
)


def classify_extension(ext: str) -> Literal["allow", "deny", "other"]:
    """按扩展名返回 allow / deny / other。"""
    if ext in ALLOW_EXTS:
        return "allow"
    if ext in DENY_EXTS:
        return "deny"
    return "other"
