function confirmed = defaultConfirm(parent, sanitizedText)
%DEFAULTCONFIRM Ask the user before sending the immutable sanitized snapshot.

message = sprintf("%s\n\n%s", mxa.bridge.MatlabBridgeApp.SafetyPrompt, sanitizedText);
choice = uiconfirm( ...
    parent, ...
    message, ...
    "发送诊断信息?", ...
    "Options", ["发送", "Cancel"], ...
    "DefaultOption", "Cancel", ...
    "CancelOption", "Cancel");

confirmed = strcmp(choice, "发送");
end
