function [title, confirmOption, details] = defaultConfirmCopy(context)
%DEFAULTCONFIRMCOPY Frozen confirmation copy for bridge consent dialogs.

contextText = string(context);
if contextText == "run_state_persistence"
    title = "保存运行状态快照?";
    confirmOption = "保存";
    details = strjoin([ ...
        "数据类别: 已脱敏、降采样的 MATLAB/Simulink 运行状态摘要,不含原始 MAT/CSV 文件。", ...
        "用途: 保存本轮 run-state,用于跨轮状态机和后续本地会话衔接。", ...
        "持久化: 确认后会写入本机 mxa-tutor SQLite 存储。", ...
        "最长留存: 最长不超过 24h,可能更早删除。", ...
        "删除条件: 工程删除、会话结束/失效或留存到期会删除。" ...
    ], newline);
elseif contextText == "run_state_coaching"
    title = "发送运行状态陪调请求?";
    confirmOption = "发送";
    details = strjoin([ ...
        "数据类别: 已脱敏、降采样的 MATLAB/Simulink 运行状态摘要,不含原始 MAT/CSV 文件。", ...
        "用途: 发送给 LLM 生成本轮 run-state 陪调,并用于后续跨轮指导。", ...
        "第三方与留存: 由第三方 LLM 服务 DeepSeek 生成;其服务端留存不由本机 24h 控制;本机不持久化解释或上下文。", ...
        "范围: 目标 run + 最多 previous_run_count 前序;实际所用轮会在结果中回显。" ...
    ], newline);
else
    title = "发送诊断信息?";
    confirmOption = "发送";
    details = "";
end
end
