function sanitized = redactDiagnosticText(inputText)
%REDACTDIAGNOSTICTEXT Best-effort absolute path redaction before confirmation.

sanitized = string(inputText);
patterns = { ...
    'file://[^\s''"<>]+', ...
    '\\\\[A-Za-z0-9._$-]+\\[^\s''"<>]+', ...
    '[A-Za-z]:[\\/][^\s''"<>]+', ...
    '/(?:Users|home|tmp|var|opt|mnt|Volumes)/[^\s''"<>]+' ...
};

for index = 1:numel(patterns)
    sanitized = regexprep(sanitized, patterns{index}, "[REDACTED_PATH]");
end
end
