function sanitized = redactDiagnosticText(inputText)
%REDACTDIAGNOSTICTEXT Best-effort path/secret/source redaction before confirmation.

sanitized = string(inputText);
pathPatterns = { ...
    'file://[^\s''"<>]+', ...
    '\\\\[A-Za-z0-9._$-]+\\[^\s''"<>]+', ...
    '[A-Za-z]:[\\/][^\s''"<>]+', ...
    '/(?:Users|home|tmp|var|opt|mnt|Volumes)/[^\s''"<>]+' ...
};
secretPatterns = { ...
    '([Aa][Pp][Ii][_-]?[Kk][Ee][Yy]|[Ss][Ee][Cc][Rr][Ee][Tt]|[Tt][Oo][Kk][Ee][Nn]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd])\s*[:=]\s*[^\s''"<>]{8,}', ...
    '\bsk-[A-Za-z0-9]{10,}\b' ...
};
sourcePatterns = { ...
    '^\s*function[^\n\r]*', ...
    '\n\s*function[^\n\r]*', ...
    '^\s*classdef[^\n\r]*', ...
    '\n\s*classdef[^\n\r]*', ...
    '^\s*#include[^\n\r]*', ...
    '\n\s*#include[^\n\r]*' ...
};

for index = 1:numel(pathPatterns)
    sanitized = regexprep(sanitized, pathPatterns{index}, "[REDACTED_PATH]");
end
for index = 1:numel(secretPatterns)
    sanitized = regexprep(sanitized, secretPatterns{index}, "[REDACTED_SECRET]");
end
for index = 1:numel(sourcePatterns)
    sanitized = regexprep(sanitized, sourcePatterns{index}, "[REDACTED_SOURCE]");
end
end
