"""ProjectNode.id generation and parsing helpers.

All node IDs should be generated by the ``make_*`` helpers in this module.
Callers should parse IDs through ``parse_node_id`` instead of splitting the
string by hand.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from core.domain.project_graph import NodeType

__all__ = [
    "ParsedNodeId",
    "make_block_id",
    "make_file_m_id",
    "make_file_mat_id",
    "make_file_slx_id",
    "make_function_id",
    "make_subsystem_id",
    "parse_node_id",
]

PREFIX_SEP = ":"
INNER_SEP = "::"


def make_file_m_id(relpath: str) -> str:
    """Return ``m:<relpath>``."""
    return f"m{PREFIX_SEP}{relpath}"


def make_function_id(relpath: str, function_name: str) -> str:
    """Return ``m:<relpath>::fn:<function_name>``."""
    return f"m{PREFIX_SEP}{relpath}{INNER_SEP}fn{PREFIX_SEP}{function_name}"


def make_file_slx_id(relpath: str) -> str:
    """Return ``slx:<relpath>``."""
    return f"slx{PREFIX_SEP}{relpath}"


def make_block_id(slx_relpath: str, block_id: str) -> str:
    """Return ``slx:<slx_relpath>::block:<block_id>``."""
    return f"slx{PREFIX_SEP}{slx_relpath}{INNER_SEP}block{PREFIX_SEP}{block_id}"


def make_subsystem_id(slx_relpath: str, subsystem_name: str) -> str:
    """Return ``slx:<slx_relpath>::sub:<subsystem_name>``."""
    return f"slx{PREFIX_SEP}{slx_relpath}{INNER_SEP}sub{PREFIX_SEP}{subsystem_name}"


def make_file_mat_id(relpath: str) -> str:
    """Return ``mat:<relpath>``."""
    return f"mat{PREFIX_SEP}{relpath}"


@dataclass(frozen=True)
class ParsedNodeId:
    """Structured result from ``parse_node_id``."""

    node_type: NodeType
    relpath: str
    inner_kind: Literal["fn", "block", "sub"] | None = None
    inner_value: str | None = None


def parse_node_id(node_id: str) -> ParsedNodeId:
    """Parse a ProjectGraph node ID into structured parts.

    Args:
        node_id: ID generated by one of this module's ``make_*`` helpers.

    Returns:
        Parsed ID with node type, relative path, and optional child marker.

    Raises:
        ValueError: If the ID shape is not recognized.
    """
    if PREFIX_SEP not in node_id:
        raise ValueError(f"invalid node_id (no prefix sep): {node_id!r}")
    prefix, _, rest = node_id.partition(PREFIX_SEP)

    if INNER_SEP in rest:
        relpath, _, inner = rest.partition(INNER_SEP)
        if PREFIX_SEP not in inner:
            raise ValueError(f"invalid inner (no sep): {node_id!r}")
        inner_kind, _, inner_value = inner.partition(PREFIX_SEP)
    else:
        relpath = rest
        inner_kind = None
        inner_value = None

    mapping: dict[tuple[str, str | None], NodeType] = {
        ("m", None): NodeType.FILE_M,
        ("m", "fn"): NodeType.FUNCTION,
        ("slx", None): NodeType.FILE_SLX,
        ("slx", "block"): NodeType.BLOCK,
        ("slx", "sub"): NodeType.SUBSYSTEM,
        ("mat", None): NodeType.FILE_MAT,
    }
    key = (prefix, inner_kind)
    if key not in mapping:
        raise ValueError(f"unknown node_id pattern: {node_id!r}")

    if inner_kind in {"fn", "block", "sub"}:
        assert inner_value is not None, "inner_kind requires inner_value"
        if inner_value == "":
            raise ValueError(f"empty inner_value: {node_id!r}")

    return ParsedNodeId(
        node_type=mapping[key],
        relpath=relpath,
        inner_kind=inner_kind,  # type: ignore[arg-type]
        inner_value=inner_value,
    )
